### ISSUE TITLE
Build fails on ubuntu-22.04-amd64 with liburcu 0.13.1

### ISSUE THREAD

**Issue by anrxc** [gdnsd/gdnsd#220]
Hello, this userspace-rcu/liburcu commit that made it into 0.13.1 release breaks the build of gdnsd-3.8.x on ubuntu-22.04-amd64 and centos-7-aarch64: 

https://bugs.lttng.org/projects/urcu/repository/userspace-rcu/revisions/1e41ec3b07e4f8eb71c3ace758c76a7ad1784c73/diff/include/urcu/static/pointer.h

```
  CC       libgdmaps/dclists.o
In file included from /usr/include/x86_64-linux-gnu/urcu/pointer.h:39,
                 from /usr/include/x86_64-linux-gnu/urcu/urcu-qsbr.h:40,
                 from /usr/include/x86_64-linux-gnu/urcu-qsbr.h:2,
                 from libgdmaps/gdmaps.c:52:
libgdmaps/gdmaps.c: In function 'gdmap_lookup':
libgdmaps/gdmaps.c:468:36: error: invalid use of undefined type 'struct dclists'
  468                                     rcu_dereference(gdmap->dclists),
                                          ^~~~~~~~~~~~~~~
make[3]: *** [Makefile:1212: libgdmaps/gdmaps.o] Error 1
```

**Comment by paravoid** [comment]
I've just confirmed that 3.8.0 builds on Ubuntu 22.04 (liburcu 0.13.1) fail, but current git master (with PR #221) does not.

I've also confirmed that Debian sid (liburcu 0.13.2) builds continue to work with current git master.

@blblack I think you can safely resolve this issue :)
