### ISSUE TITLE
gdnsd 3.0.1 fails to build on macOS

### ISSUE THREAD

**Issue by fxcoudert** [gdnsd/gdnsd#180]
gdnsd 3.0.1 fails to build on all macOS versions (10.12 to 10.14), because `SOCK_NONBLOCK` and `SOCK_CLOEXEC` don't exist there:

```
src/plugins/http_status.c:118:70: error: use of undeclared identifier 'SOCK_NONBLOCK'
    const int sock = socket(isv6 ? PF_INET6 : PF_INET, SOCK_STREAM | SOCK_NONBLOCK | SOCK_CLOEXEC, IPPROTO_TCP);
                                                                     ^
src/plugins/http_status.c:118:86: error: use of undeclared identifier 'SOCK_CLOEXEC'
    const int sock = socket(isv6 ? PF_INET6 : PF_INET, SOCK_STREAM | SOCK_NONBLOCK | SOCK_CLOEXEC, IPPROTO_TCP);
                                                                                     ^
```

This is preventing us from shipping that version in Homebrew: https://github.com/Homebrew/homebrew-core/pull/37599

**Comment by blblack** [comment]
I assume that the `accept4()` syscall itself still also doesn't exist on MacOS?  It wouldn't make much sense to have an `accept4()` without at least one of those flags available.  `make -k` ("keep going") might deliver a fuller report of all the things that fail at the compilation level, so we can capture any other gdnsd-3 + MacOS issues and fix it all in one go?

On the broader topic, what I've said for gdnsd-3 in the documentation is: `MacOS/Darwin is no longer supported.  I don't happen to have a Mac around, they don't allow emulation, and they don't make server hardware.  The code may happen to build and/or run successfully there by virtue of the code's general BSD compatibility, but I think that's unlikely with recent gdnsd and MacOS versions.`

The lack of `SOCK_CLOEXEC` and `accept4()` makes our execution model have potential race conditions that leak sockets, and thus it wouldn't be suitable to really treat it as a supported server platform.  But I'd be amenable to doing the workarounds for those cases; they're all relatively-easy to fix.  I think, if we go down that road and get Macs building again though, I'd want to declare that it's for only for the purpose of development or CI (e.g. having a gdnsd binary installed on your laptop makes it easier to CI-check your DNS zonefiles in a local git clone for errors by running `gdnsd checkconf`).

**Comment by blblack** [comment]
Apparently the homebrew people don't want to debug further and deleted it instead, so maybe we'll wait and see if someone else actually care enough to find the issues!
